2023-08-24 13:55:20 - INFO - [base_logger.py : create_logger_for_service - 34] :: Initialized logger for the service [registration] :: [SUCCESS]
2023-08-24 13:55:20 - INFO - [create_app.py : create_app_instance - 55] :: Received Service [registration]
2023-08-24 13:55:20 - INFO - [create_app.py : create_app_instance - 57] :: Flask of Application Instance created for service [registration] ,  App Name :: [<Flask 'registration'>] ==> SUCCESS
2023-08-24 13:55:20 - INFO - [create_app.py : read_json_schema - 267] :: Received Schema File Path : /Users/kamalsaidevarapalli/Desktop/Workshop/AirlinerAdminstration/src/registration_service/schemas/headers/reg_headers_schema.json
2023-08-24 13:55:20 - INFO - [create_app.py : read_json_schema - 277] :: Schema Validation True
2023-08-24 13:55:20 - INFO - [create_app.py : read_json_schema - 267] :: Received Schema File Path : /Users/kamalsaidevarapalli/Desktop/Workshop/AirlinerAdminstration/src/registration_service/schemas/requests/register_user/req_schema.json
2023-08-24 13:55:20 - INFO - [create_app.py : read_json_schema - 277] :: Schema Validation True
2023-08-24 13:55:20 - INFO - [create_app.py : create_blueprint - 74] :: Created Blueprint :: <Blueprint 'registration_bp'> for the Application service ::registration
2023-08-24 13:55:20 - INFO - [create_app.py : display_registered_blueprints_for_service - 106] :: Added Blueprints :: /static/<path:filename>
2023-08-24 13:55:20 - INFO - [create_app.py : create_db_engine - 125] :: Creating DB-Engine using DatabaseURI for Service :: [registration]
2023-08-24 13:55:20 - INFO - [create_app.py : get_database_uri - 116] :: Preparing DatabaseURI for Service :: [registration]
2023-08-24 13:55:20 - INFO - [create_app.py : get_database_uri - 118] :: Prepared DatabaseURI for Service :: [registration] - postgresql://airlineradmin:Ishi#06041995@127.0.0.1:3304/REGISTRATIONS
2023-08-24 13:55:20 - INFO - [create_app.py : check_database_connectivity - 217] :: Current Connection status set to :: False for the service :: registration
2023-08-24 13:55:20 - INFO - [create_app.py : check_database_connectivity - 218] :: Trying to establish the connection to the database :: [IN-PROGRESS]
