2023-08-23 20:42:33 - INFO - [base_logger.py : 34] :: Initialized logger for the service [authtoken] :: [SUCCESS]
2023-08-23 20:42:33 - INFO - [create_app.py : 42] :: Received Service [authtoken]
2023-08-23 20:42:33 - INFO - [create_app.py : 44] :: Flask of Application Instance created for service [authtoken] ,  App Name :: [<Flask 'authtoken'>] ==> SUCCESS
2023-08-23 20:42:33 - INFO - [create_app.py : 53] :: Created Blueprint :: <Blueprint 'authtoken_bp'> for the Application service ::authtoken
2023-08-23 20:42:33 - INFO - [create_app.py : 70] :: Added Blueprints :: /static/<path:filename>
2023-08-23 20:42:33 - INFO - [create_app.py : 80] :: Creating DB-Engine using DatabaseURI for Service :: [authtoken]
2023-08-23 20:42:33 - INFO - [create_app.py : 74] :: Preparing DatabaseURI for Service :: [authtoken]
2023-08-23 20:42:33 - INFO - [create_app.py : 76] :: Prepared DatabaseURI for Service :: [authtoken] - mysql+pymysql://root:Ishi#06041995@127.0.0.1:3305/AUTHTOKENS
2023-08-23 20:42:33 - INFO - [create_app.py : 82] :: Created DB-Engine using DatabaseURIfor Service :: [Engine(mysql+pymysql://root:***@127.0.0.1:3305/AUTHTOKENS)]
2023-08-23 20:42:33 - INFO - [create_app.py : 111] :: Current Connection status set to :: False for the service :: authtoken
2023-08-23 20:42:33 - INFO - [create_app.py : 112] :: Trying to establish the connection to the database :: [IN-PROGRESS]
2023-08-23 20:42:33 - INFO - [create_app.py : 116] :: Established the connection to the database :: [SUCCESS]
2023-08-23 20:42:33 - INFO - [create_app.py : 118] :: Current Connection status set to :: True for the service :: authtoken
2023-08-23 20:42:33 - INFO - [create_app.py : 120] :: Closing the Current Connection as the connection was established for the service :: authtoken
2023-08-23 20:42:33 - INFO - [create_app.py : 153] :: Database already exists :: AUTHTOKENS
2023-08-23 20:42:33 - INFO - [create_app.py : 129] :: Trying to create the tables if not present in the database...
2023-08-23 20:42:33 - INFO - [create_app.py : 131] :: Going to create the tables ...
2023-08-23 20:42:33 - INFO - [create_app.py : 134] :: Created the tables ...
2023-08-23 20:42:33 - INFO - [create_app.py : 87] :: Binding SQLALCHEMY using DatabaseURI:: [mysql+pymysql://root:Ishi#06041995@127.0.0.1:3305/AUTHTOKENS] to Application Instance for Service :: [authtoken]
2023-08-23 20:42:33 - INFO - [create_app.py : 89] :: Binded SQLALCHEMY :: [<SQLAlchemy>] to Application Instance for Service :: [authtoken]
2023-08-23 20:42:33 - INFO - [create_app.py : 93] :: Initialized Pool for Service ==>[authtoken] :: [SUCCESS]
2023-08-23 20:42:33 - INFO - [create_app.py : 162] :: #---------------------------------[ POOL - INFO ]----------------------------------------#
2023-08-23 20:42:33 - INFO - [create_app.py : 163] :: Displaying Pool_Info for Service ==>[authtoken] 
2023-08-23 20:42:33 - INFO - [create_app.py : 164] :: Current Pool Info :: <sqlalchemy.pool.impl.QueuePool object at 0x106b52f70> - ID: 4407504752
2023-08-23 20:42:33 - INFO - [create_app.py : 165] :: Current Pool Size ::  100
2023-08-23 20:42:33 - INFO - [create_app.py : 166] :: Checked Out Connections from Pool  0
2023-08-23 20:42:33 - INFO - [create_app.py : 167] :: Checked in Connections available in Pool :: 0
2023-08-23 20:42:33 - INFO - [create_app.py : 168] :: Current Pool Overflow Info :: -100
2023-08-23 20:42:33 - INFO - [create_app.py : 169] :: #---------------------------------[ POOL - INFO ]----------------------------------------#
2023-08-23 20:42:33 - INFO - [create_app.py : 57] :: Registering blueprints to the service :: <Flask 'authtoken'>
2023-08-23 20:42:33 - INFO - [create_app.py : 70] :: Added Blueprints :: /static/<path:filename>
2023-08-23 20:42:33 - INFO - [create_app.py : 70] :: Added Blueprints :: /api/v1/airliner/generateToken
2023-08-23 20:42:33 - INFO - [create_app.py : 61] :: Registering Error Handler 500-<function internal_server_error at 0x107e54160> to the service :: <Flask 'authtoken'>
2023-08-23 20:42:33 - INFO - [create_app.py : 61] :: Registering Error Handler 400-<function bad_request at 0x107e48af0> to the service :: <Flask 'authtoken'>
2023-08-23 20:42:33 - INFO - [create_app.py : 61] :: Registering Error Handler 404-<function not_found at 0x107e541f0> to the service :: <Flask 'authtoken'>
2023-08-23 20:42:33 - INFO - [create_app.py : 66] :: Error Code: None, Handler Function: {}
2023-08-23 20:42:33 - INFO - [token_app.py : 5] :: Started the AUTH TOKEN server ...
2023-08-23 20:42:33 - INFO - [token_app.py : 6] :: Application is ready to server traffic.
2023-08-23 20:42:41 - INFO - [authtoken_controller.py : 15] :: REQUEST ==> Received Endpoint :: authtoken_bp.create_token
2023-08-23 20:42:41 - INFO - [authtoken_controller.py : 17] :: Received Headers from the request :: {'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/7.32.3', 'Accept': '*/*', 'Host': '127.0.0.1:9092', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive', 'Content-Length': '81'}
2023-08-23 20:42:41 - INFO - [authtoken_controller.py : 18] :: Validation for Request-Header is  :: [STARTED]
2023-08-23 20:42:41 - INFO - [authtoken_controller.py : 21] :: Validation for Request-Header is  :: [SUCCESS]
2023-08-23 20:42:41 - INFO - [authtoken_controller.py : 24] :: Validation for Request-Body is  :: [STARTED]
2023-08-23 20:42:41 - INFO - [create_app.py : 175] :: Creating session using pool of connections  :: [STARTED]
2023-08-23 20:42:41 - INFO - [create_app.py : 176] :: Creating session using Pool_info :: <sqlalchemy.pool.impl.QueuePool object at 0x106b52f70>
2023-08-23 20:42:41 - INFO - [create_app.py : 177] :: Initialising  a session maker for database interactions
2023-08-23 20:42:41 - INFO - [create_app.py : 179] :: Initialised a session maker for database interactions sessionmaker(class_='Session', bind=Engine(mysql+pymysql://root:***@127.0.0.1:3305/AUTHTOKENS), autoflush=True, expire_on_commit=True)
2023-08-23 20:42:41 - INFO - [create_app.py : 181] :: Created session to store the data in to DataBase Session-Id  :: <sqlalchemy.orm.session.Session object at 0x107fa2040>
2023-08-23 20:42:41 - INFO - [create_app.py : 162] :: #---------------------------------[ POOL - INFO ]----------------------------------------#
2023-08-23 20:42:41 - INFO - [create_app.py : 163] :: Displaying Pool_Info for Service ==>[authtoken] 
2023-08-23 20:42:41 - INFO - [create_app.py : 164] :: Current Pool Info :: <sqlalchemy.pool.impl.QueuePool object at 0x106b52f70> - ID: 4407504752
2023-08-23 20:42:41 - INFO - [create_app.py : 165] :: Current Pool Size ::  100
2023-08-23 20:42:41 - INFO - [create_app.py : 166] :: Checked Out Connections from Pool  0
2023-08-23 20:42:41 - INFO - [create_app.py : 167] :: Checked in Connections available in Pool :: 0
2023-08-23 20:42:41 - INFO - [create_app.py : 168] :: Current Pool Overflow Info :: -100
2023-08-23 20:42:41 - INFO - [create_app.py : 169] :: #---------------------------------[ POOL - INFO ]----------------------------------------#
2023-08-23 20:42:41 - INFO - [authtoken_controller.py : 32] :: Checking for the token which is already exists or not for the user
2023-08-23 20:42:41 - INFO - [authtoken_controller.py : 35] :: Token not exists, so Validating whether it is registered user  :: [STARTED]
2023-08-23 20:42:41 - INFO - [authtoken_controller.py : 36] :: Sending gRPC message to Registration Service :: [STARTED]
2023-08-23 20:42:41 - INFO - [client.py : 14] :: Request Created  :: userid: "46"
username: "kamal4"
passcode: "Ishi#06041995"

2023-08-23 20:42:41 - INFO - [client.py : 26] :: Created channel :: <grpc._channel.Channel object at 0x107fbf0a0>
2023-08-23 20:42:41 - INFO - [client.py : 28] :: Created Stub and assigned to the channel :: <src.airliner_grpc.token_pb2_grpc.UserValidationForTokenGenerationStub object at 0x111c3a430>
2023-08-23 20:42:41 - INFO - [client.py : 40] :: Received Response from grpc :: userid: "46"
isvalid: true

2023-08-23 20:42:41 - INFO - [authtoken_controller.py : 42] :: gRPC Response data :: userid: "46"
isvalid: true
, Response status :: True
2023-08-23 20:42:42 - INFO - [authtoken_controller.py : 45] :: Valid User, need to create a new token
2023-08-23 20:42:42 - INFO - [authtoken_controller.py : 54] :: Data added into  DataBase session TokenID='None', UserID='46',         Token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY5Mjg0ODU2MiwianRpIjoiMzAwMmY3MWUtNWQ5Yy00MDA2LTlhN2YtOTIyZDlkN2VmZjA1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjQ2IiwibmJmIjoxNjkyODQ4NTYyLCJleHAiOjE2OTI4NDk0NjJ9.nhsV6_IYa92Z3fiyNrrceKE5nBO5iNu_KFutekOO5Bg', Expiry='10000',         CreatedAt='2023-08-23 20:42:33.486455', UpdatedAt='2023-08-23 20:42:33.486463':: [SUCCESS]
2023-08-23 20:42:42 - INFO - [authtoken_controller.py : 56] :: Added Data is committed into  DataBase <sqlalchemy.orm.session.Session object at 0x107fa2040>:: [SUCCESS]
2023-08-23 20:42:42 - INFO - [authtoken_controller.py : 58] :: Generating Success response  :: [STARTED]
2023-08-23 20:42:42 - INFO - [authtoken_controller.py : 61] :: Generating Success response  :: [STARTED] :: {'message': 'Token  is created', 'token': {'accessToken': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY5Mjg0ODU2MiwianRpIjoiMzAwMmY3MWUtNWQ5Yy00MDA2LTlhN2YtOTIyZDlkN2VmZjA1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjQ2IiwibmJmIjoxNjkyODQ4NTYyLCJleHAiOjE2OTI4NDk0NjJ9.nhsV6_IYa92Z3fiyNrrceKE5nBO5iNu_KFutekOO5Bg', 'expiresIn': '10000'}}
